### ISSUE TITLE
Gitguardian action needs an API key, fails all tests

### ISSUE THREAD

**Issue by alfredodeza** [microsoft/workshop-library#62]
Because the current GitGuardian action needs an API key, it fails all verifications for PRs

```
Traceback (most recent call last):
  File "/app/.venv/bin/ggshield", line 33, in <module>
    sys.exit(load_entry_point('ggshield', 'console_scripts', 'ggshield')())
  File "/app/ggshield/cmd.py", line 229, in cli_wrapper
    return_code: int = cli.main(standalone_mode=False)
  File "/app/.venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/app/.venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.venv/lib/python3.9/site-packages/click/core.py", line 1656, in invoke
    super().invoke(ctx)
  File "/app/.venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/.venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/.venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/ggshield/cmd.py", line [12](https://github.com/microsoft/workshop-library/runs/5482063486?check_suite_focus=true#step:4:12)1, in scan
    ctx.obj["client"] = retrieve_client(ctx)
  File "/app/ggshield/utils.py", line [24](https://github.com/microsoft/workshop-library/runs/5482063486?check_suite_focus=true#step:4:24)8, in retrieve_client
    raise click.ClickException("GitGuardian API Key is needed.")
click.exceptions.ClickException: GitGuardian API Key is needed.
```

**Comment by jlooper** [comment]
There's something strange going on - part of GitGuardian succeeds and part fails consistently. Looking into it...there's a key stored in this repo in the Secrets area.

**Comment by jlooper** [comment]
I've made a change, let's see how it works going forward

**Comment by alfredodeza** [comment]
So this is always going to be a problem with secrets and actions in the current format we have. According to the GitHub docs:

> Secrets are not passed to workflows that are triggered by a pull request from a fork.

Which is the case for pretty much every PR in this repository
